# Generated by Django 2.0.2 on 2018-05-09 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180509_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
