# Generated by Django 2.0.2 on 2018-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_time_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='file_path',
            field=models.FilePathField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
