# Generated by Django 2.0.2 on 2018-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180509_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='file_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
