# Generated by Django 2.0.2 on 2018-05-09 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180509_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='file_path',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cars'),
            preserve_default=False,
        ),
    ]
