# Generated by Django 2.0.2 on 2018-05-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20180509_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='photo',
        ),
    ]
