# Generated by Django 2.0.2 on 2018-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_restaurant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
